// <auto-generated />
using System;
using Cobrio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cobrio.Infrastructure.Migrations
{
    [DbContext(typeof(CobrioDbContext))]
    partial class CobrioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cobrio.Domain.Entities.Acao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique()
                        .HasDatabaseName("uk_acao_chave");

                    b.HasIndex("TipoAcao")
                        .HasDatabaseName("idx_acao_tipo");

                    b.ToTable("Acao", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Assinante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CPFCNPJ")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFimCiclo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFimTrial")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("int");

                    b.Property<bool>("EmTrial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("PlanoOfertaId")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("ProximaCobranca")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoOfertaId")
                        .HasDatabaseName("idx_plano");

                    b.HasIndex("ProximaCobranca")
                        .HasDatabaseName("idx_proxima_cobranca");

                    b.HasIndex("EmpresaClienteId", "Email")
                        .HasDatabaseName("idx_tenant_email");

                    b.HasIndex("EmpresaClienteId", "ProximaCobranca")
                        .HasDatabaseName("idx_tenant_proxima_cobranca");

                    b.HasIndex("EmpresaClienteId", "Status")
                        .HasDatabaseName("idx_tenant_status");

                    b.ToTable("Assinante", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Cobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDisparo")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("DATE");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegraCobrancaId")
                        .HasColumnType("CHAR(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TentativasEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("idx_cobranca_data_vencimento");

                    b.HasIndex("RegraCobrancaId", "Status")
                        .HasDatabaseName("idx_cobranca_regra_status");

                    b.HasIndex("Status", "TentativasEnvio")
                        .HasDatabaseName("idx_cobranca_status_tentativas");

                    b.HasIndex("EmpresaClienteId", "Status", "DataDisparo")
                        .HasDatabaseName("idx_cobranca_tenant_status_disparo");

                    b.ToTable("Cobranca", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.EmpresaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("CHAR(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataContrato")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PlanoCobrioId")
                        .HasColumnType("int");

                    b.Property<string>("StatusContrato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasDatabaseName("idx_cnpj");

                    b.HasIndex("PlanoCobrioId")
                        .HasDatabaseName("idx_plano");

                    b.HasIndex("StatusContrato")
                        .HasDatabaseName("idx_status");

                    b.ToTable("EmpresaCliente", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("AssinanteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Desconto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DescontoCentavos")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<long>("Impostos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ImpostosCentavos")
                        .HasDefaultValueSql("0");

                    b.Property<string>("LinkBoleto")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MetodoPagamentoId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("NumeroFatura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCodePix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("'Pendente'");

                    b.Property<string>("TransacaoIdGateway")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("ValorBruto")
                        .HasColumnType("bigint")
                        .HasColumnName("ValorBrutoCentavos");

                    b.Property<long>("ValorLiquido")
                        .HasColumnType("bigint")
                        .HasColumnName("ValorLiquidoCentavos");

                    b.Property<string>("_moeda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(3)")
                        .HasDefaultValue("BRL")
                        .HasColumnName("Moeda");

                    b.HasKey("Id");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("idx_data_vencimento");

                    b.HasIndex("MetodoPagamentoId");

                    b.HasIndex("AssinanteId", "Status")
                        .HasDatabaseName("idx_assinante_status");

                    b.HasIndex("EmpresaClienteId", "DataVencimento")
                        .HasDatabaseName("idx_tenant_vencimento");

                    b.HasIndex("EmpresaClienteId", "NumeroFatura")
                        .IsUnique()
                        .HasDatabaseName("uk_numero_fatura");

                    b.HasIndex("EmpresaClienteId", "Status")
                        .HasDatabaseName("idx_tenant_status");

                    b.HasIndex("Status", "DataVencimento")
                        .HasDatabaseName("idx_status_vencimento");

                    b.ToTable("Fatura", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.HistoricoImportacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("ErrosJson")
                        .HasColumnType("LONGTEXT");

                    b.Property<int>("LinhasComErro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("LinhasProcessadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.Property<Guid>("RegraCobrancaId")
                        .HasColumnType("CHAR(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalLinhas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_historico_importacao_status");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EmpresaClienteId", "DataImportacao")
                        .HasDatabaseName("idx_historico_importacao_tenant_data");

                    b.HasIndex("RegraCobrancaId", "DataImportacao")
                        .HasDatabaseName("idx_historico_importacao_regra_data");

                    b.ToTable("HistoricoImportacao", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.HistoricoNotificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CanalUtilizado")
                        .HasColumnType("int");

                    b.Property<Guid>("CobrancaId")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("MensagemEnviada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadUtilizado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegraCobrancaId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("RespostaProvedor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanalUtilizado", "Status")
                        .HasDatabaseName("idx_historico_canal_status");

                    b.HasIndex("CobrancaId", "Status")
                        .HasDatabaseName("idx_historico_cobranca_status");

                    b.HasIndex("EmpresaClienteId", "DataEnvio")
                        .HasDatabaseName("idx_historico_tenant_data");

                    b.HasIndex("RegraCobrancaId", "Status")
                        .HasDatabaseName("idx_historico_regra_status");

                    b.HasIndex("Status", "DataEnvio")
                        .HasDatabaseName("idx_historico_status_data");

                    b.ToTable("HistoricoNotificacao", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.ItemFatura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("FaturaId")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid?>("PlanoOfertaId")
                        .HasColumnType("CHAR(36)");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'Plano'");

                    b.Property<long>("ValorTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("ValorTotalCentavos");

                    b.Property<long>("ValorUnitario")
                        .HasColumnType("bigint")
                        .HasColumnName("ValorUnitarioCentavos");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId")
                        .HasDatabaseName("idx_fatura");

                    b.HasIndex("PlanoOfertaId");

                    b.ToTable("ItemFatura", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.MetodoPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("AssinanteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Bandeira")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("GatewayProvider")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomeTitular")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TokenGateway")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UltimosDigitos")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("AssinanteId")
                        .HasDatabaseName("idx_assinante");

                    b.HasIndex("AssinanteId", "Principal")
                        .HasDatabaseName("idx_assinante_principal");

                    b.HasIndex("EmpresaClienteId", "Ativo")
                        .HasDatabaseName("idx_tenant_ativo");

                    b.ToTable("MetodoPagamento", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("pi-circle");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique()
                        .HasDatabaseName("uk_modulo_chave");

                    b.HasIndex("Ordem")
                        .HasDatabaseName("idx_modulo_ordem");

                    b.ToTable("Modulo", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.PermissaoPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("AcaoId")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("PerfilUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Permitido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("EmpresaClienteId", "PerfilUsuario")
                        .HasDatabaseName("idx_permissao_empresa_perfil");

                    b.HasIndex("EmpresaClienteId", "PerfilUsuario", "ModuloId", "AcaoId")
                        .IsUnique()
                        .HasDatabaseName("uk_permissao_empresa_perfil_modulo_acao");

                    b.ToTable("PermissaoPerfil", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.PlanoOferta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<int?>("LimiteUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PeriodoTrialDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("PeriodoTrial");

                    b.Property<bool>("PermiteDowngrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("PermiteUpgrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("TipoCiclo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("Valor")
                        .HasColumnType("bigint")
                        .HasColumnName("ValorCentavos");

                    b.Property<string>("_moeda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(3)")
                        .HasDefaultValue("BRL")
                        .HasColumnName("Moeda");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaClienteId", "Ativo")
                        .HasDatabaseName("idx_tenant_ativo");

                    b.HasIndex("EmpresaClienteId", "Nome")
                        .HasDatabaseName("idx_tenant_nome");

                    b.ToTable("PlanoOferta", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UsuarioEmpresaId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_token");

                    b.HasIndex("UsuarioEmpresaId", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("idx_usuario_ativo");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.RegraCobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CanalNotificacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("EhPadrao")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TemplateNotificacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoMomento")
                        .HasColumnType("int");

                    b.Property<string>("TokenWebhook")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("UnidadeTempo")
                        .HasColumnType("int");

                    b.Property<int>("ValorTempo")
                        .HasColumnType("int");

                    b.Property<string>("VariaveisObrigatorias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VariaveisObrigatoriasSistema")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TokenWebhook")
                        .IsUnique()
                        .HasDatabaseName("idx_regra_cobranca_token");

                    b.HasIndex("EmpresaClienteId", "Ativa")
                        .HasDatabaseName("idx_regra_cobranca_tenant_ativa");

                    b.HasIndex("EmpresaClienteId", "CanalNotificacao")
                        .HasDatabaseName("idx_regra_cobranca_tenant_canal");

                    b.ToTable("RegraCobranca", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.ReguaDunningConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiasCancelamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<int>("DiasSuspensao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15);

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<bool>("EnviarEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnviarNotificacaoInApp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnviarSMS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan>("HoraFimRetry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time(6)")
                        .HasDefaultValue(new TimeSpan(0, 20, 0, 0, 0));

                    b.Property<TimeSpan>("HoraInicioRetry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time(6)")
                        .HasDefaultValue(new TimeSpan(0, 8, 0, 0, 0));

                    b.Property<string>("IntervalosDias")
                        .IsRequired()
                        .HasColumnType("JSON")
                        .HasColumnName("IntervalosDiasJson");

                    b.Property<int>("NumeroMaximoTentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.HasKey("Id");

                    b.HasIndex("EmpresaClienteId")
                        .IsUnique();

                    b.ToTable("ReguaDunningConfig", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.TentativaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CodigoErro")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataTentativa")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("FaturaId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("GatewayProvider")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroTentativa")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TransacaoIdGateway")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId")
                        .HasDatabaseName("idx_fatura");

                    b.HasIndex("Resultado")
                        .HasDatabaseName("idx_resultado");

                    b.HasIndex("EmpresaClienteId", "DataTentativa")
                        .HasDatabaseName("idx_tenant_data");

                    b.ToTable("TentativaPagamento", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EhProprietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("EmpresaClienteId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'Operador'");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email", "EmpresaClienteId")
                        .IsUnique()
                        .HasDatabaseName("uk_email_empresa");

                    b.HasIndex("EmpresaClienteId", "Ativo")
                        .HasDatabaseName("idx_tenant_ativo");

                    b.HasIndex("EmpresaClienteId", "Email")
                        .HasDatabaseName("idx_tenant_email");

                    b.ToTable("UsuarioEmpresa", (string)null);
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Assinante", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany("Assinantes")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.PlanoOferta", "PlanoOferta")
                        .WithMany("Assinantes")
                        .HasForeignKey("PlanoOfertaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Cobrio.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("AssinanteId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Endereco_Bairro");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasColumnType("CHAR(8)")
                                .HasColumnName("Endereco_CEP");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Endereco_Cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Endereco_Complemento");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("CHAR(2)")
                                .HasColumnName("Endereco_Estado");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Endereco_Logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Endereco_Numero");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasDefaultValue("Brasil")
                                .HasColumnName("Endereco_Pais");

                            b1.HasKey("AssinanteId");

                            b1.ToTable("Assinante");

                            b1.WithOwner()
                                .HasForeignKey("AssinanteId");
                        });

                    b.Navigation("EmpresaCliente");

                    b.Navigation("Endereco");

                    b.Navigation("PlanoOferta");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Cobranca", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany()
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.RegraCobranca", "RegraCobranca")
                        .WithMany("Cobrancas")
                        .HasForeignKey("RegraCobrancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaCliente");

                    b.Navigation("RegraCobranca");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.EmpresaCliente", b =>
                {
                    b.OwnsOne("Cobrio.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("EmpresaClienteId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Endereco_Bairro");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasColumnType("CHAR(8)")
                                .HasColumnName("Endereco_CEP");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Endereco_Cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Endereco_Complemento");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("CHAR(2)")
                                .HasColumnName("Endereco_Estado");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Endereco_Logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Endereco_Numero");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasDefaultValue("Brasil")
                                .HasColumnName("Endereco_Pais");

                            b1.HasKey("EmpresaClienteId");

                            b1.ToTable("EmpresaCliente");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaClienteId");
                        });

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Fatura", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.Assinante", "Assinante")
                        .WithMany("Faturas")
                        .HasForeignKey("AssinanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany()
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.MetodoPagamento", "MetodoPagamento")
                        .WithMany()
                        .HasForeignKey("MetodoPagamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assinante");

                    b.Navigation("EmpresaCliente");

                    b.Navigation("MetodoPagamento");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.HistoricoImportacao", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany()
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.RegraCobranca", "RegraCobranca")
                        .WithMany()
                        .HasForeignKey("RegraCobrancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.UsuarioEmpresa", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("EmpresaCliente");

                    b.Navigation("RegraCobranca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.HistoricoNotificacao", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.Cobranca", "Cobranca")
                        .WithMany("Historicos")
                        .HasForeignKey("CobrancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany()
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.RegraCobranca", "RegraCobranca")
                        .WithMany()
                        .HasForeignKey("RegraCobrancaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cobranca");

                    b.Navigation("EmpresaCliente");

                    b.Navigation("RegraCobranca");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.ItemFatura", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.Fatura", "Fatura")
                        .WithMany("Itens")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.PlanoOferta", "PlanoOferta")
                        .WithMany()
                        .HasForeignKey("PlanoOfertaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fatura");

                    b.Navigation("PlanoOferta");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.MetodoPagamento", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.Assinante", "Assinante")
                        .WithMany("MetodosPagamento")
                        .HasForeignKey("AssinanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany()
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assinante");

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.PermissaoPerfil", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.Acao", "Acao")
                        .WithMany("Permissoes")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.UsuarioEmpresa", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany()
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.Modulo", "Modulo")
                        .WithMany("Permissoes")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("CriadoPor");

                    b.Navigation("EmpresaCliente");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.PlanoOferta", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany("PlanosOferta")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.UsuarioEmpresa", "UsuarioEmpresa")
                        .WithMany()
                        .HasForeignKey("UsuarioEmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioEmpresa");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.RegraCobranca", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany()
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.ReguaDunningConfig", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithOne("ReguaDunning")
                        .HasForeignKey("Cobrio.Domain.Entities.ReguaDunningConfig", "EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.TentativaPagamento", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany()
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cobrio.Domain.Entities.Fatura", "Fatura")
                        .WithMany("Tentativas")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaCliente");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.HasOne("Cobrio.Domain.Entities.EmpresaCliente", "EmpresaCliente")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Acao", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Assinante", b =>
                {
                    b.Navigation("Faturas");

                    b.Navigation("MetodosPagamento");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Cobranca", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.EmpresaCliente", b =>
                {
                    b.Navigation("Assinantes");

                    b.Navigation("PlanosOferta");

                    b.Navigation("ReguaDunning");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Fatura", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.PlanoOferta", b =>
                {
                    b.Navigation("Assinantes");
                });

            modelBuilder.Entity("Cobrio.Domain.Entities.RegraCobranca", b =>
                {
                    b.Navigation("Cobrancas");
                });
#pragma warning restore 612, 618
        }
    }
}
